version: '3.9'
services:
  my-ui-storybook:
    container_name: My-UI-Storybook
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./docker/storybook/Dockerfile
    ports:
      - '6006:6006'
    volumes:
      - ./src:/app/src
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
  my-ui:
    container_name: My-UI
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - '6007:6007'
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
