export type resetStylesProps = {
  clearIndicator: () => {},
  container: () => {},
  control: () => {},
  dropdownIndicator: () => {},
  group: () => {},
  groupHeading: () => {},
  indicatorsContainer: () => {},
  indicatorSeparator: () => {},
  input: () => {},
  loadingIndicator: () => {},
  loadingMessage: () => {},
  menu: () => {},
  menuList: () => {},
  menuPortal: () => {},
  multiValue: () => {},
  multiValueLabel: () => {},
  multiValueRemove: () => {},
  noOptionsMessage: () => {},
  option: () => {},
  placeholder: () => {},
  singleValue: () => {},
  valueContainer: () => {}
};

const resetStyles = {
  clearIndicator: () => {},
  container: () => {},
  control: () => {},
  dropdownIndicator: () => {},
  group: () => {},
  groupHeading: () => {},
  indicatorsContainer: () => {},
  indicatorSeparator: () => {},
  input: () => {},
  loadingIndicator: () => {},
  loadingMessage: () => {},
  menu: () => {},
  menuList: () => {},
  menuPortal: () => {},
  multiValue: () => {},
  multiValueLabel: () => {},
  multiValueRemove: () => {},
  noOptionsMessage: () => {},
  option: () => {},
  placeholder: () => {},
  singleValue: () => {},
  valueContainer: () => {}
};

export default resetStyles;