on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n atomfrontcr -g atomfrontcr8374-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n atomfrontcr --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n atomfrontcr --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n atomfrontcr --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: atomfrontcr.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE" -f  "docker/storybook/Dockerfile" -t atomfrontcr.azurecr.io/atomaks:${{ github.sha }} --label dockerfile-path=docker/storybook/Dockerfile
        docker push atomfrontcr.azurecr.io/atomaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_atomaks_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep atomfront | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace atomfront`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: atomfront
        container-registry-url: atomfrontcr.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: atomaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: atomfront
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          atomfrontcr.azurecr.io/atomaks:${{ github.sha }}
        imagepullsecrets: |
          atomaksdockerauth   
